#!/bin/bash
# ctclsite-python - CTCL 2020-2023
# File: runner_prod
# Purpose: Linux/BSD script for running the application in development environments
# Created: September 21, 2023
# Modified: January 9, 2024

find . -name "__pycache__" -exec rm -r "{}" 2> /dev/null \;

export CS_DEBUG="True"

function showerror {
    echo "runner_dev ERROR: Management command \"$1\" failed!"
    # Don't continue if something fails so the app does not try to run with missing files
    exit
}

python3 -B manage.py build || showerror "build"

python3 -B manage.py runserver 0.0.0.0:8000